def main():
    try:
        pass
    except Exception as e:
        print("ERROR in main ==> ", e.args)

if __name__ == "__main__":
    main()